### ISSUE TITLE
test-xmss_sign_verify fails

### ISSUE THREAD

**Issue by WeboFingerprints** [FoxCryptoNL/xmss-library#4]
Hi Dorssel,

I had a test of test-xmss_sign_verify, it worked fine on my Raspberry PI platform, but failed on my PC platform (basing on WSL of Windows). 

Error as : 
"Floating point exception (core dumped)"
OS: Linux WP2-673086 4.4.0-19041-Microsoft #4355-Microsoft Thu Apr 12 17:37:00 PST 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by dorssel** [comment]
Obviously there is something wrong with the build, which is why these tests exists. Did you configure with any specific defines? Which compiler is being used? What are the processor features (`/proc/cpuinfo`)?

The library does not use floating point operations at all. However, divide by zero, and SSE/AVX instructions may also cause this. The library does not use division, other than by simple things like `sizeof(...)`, which never are zero. And instruction optimization is processor/compiler dependent.

**Comment by WeboFingerprints** [comment]
I did not do any change on the configuration, the default gcc is gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, all compiling process is simple as being suggested in the front page.

**Comment by WeboFingerprints** [comment]
Now I try to verify the function basing on CORTEX-M33 MCU, and I need to add some compiling options in the file of compiler_options.cmake, but I always get an error as "STATIC_ASSERT(1) did not compile, but it should have" in line 58 of CMakeLists.txt under the "tests" folder. Could you please give me any suggestion as I know little about cmake?  The compiler is set as arm-none-eabi-gcc.

**Comment by dorssel** [comment]
Our tests also include arm-none-eabi-gcc. It supports C11 `static_assert()`; I don't know why yours does not.

**Comment by WeboFingerprints** [comment]
It's all fixed. Now I realized how to add compiling and linking options in the CMakeLists.txt under different folds, hence to make your project to work properly under my MCU platform. Thank you.
